AWSTemplateFormatVersion: "2010-09-09"
Description: "Create EC2 instance in any subnet with optional public IP and optional extra volume"

Parameters:
  InstanceName:
    Type: String
    Description: "EC2 Instance Name"

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: "VPC ID"

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: "KeyPair name for SSH access"

  InstanceType:
    Type: String
    Default: t2.micro
    Description: "EC2 Instance Type"

  AMIId:
    Type: AWS::EC2::Image::Id
    Description: "AMI ID to use"

  SubnetExportName:
    Type: String
    Description: "Exported name of the Subnet (public or private)"

  AssignPublicIp:
    Type: String
    AllowedValues: ["true", "false"]
    Default: "false"
    Description: "Whether to assign a public IP address to the instance"

  RootVolumeSize:
    Type: Number
    Default: 8
    Description: "Size (GiB) of the root volume"

  AttachExtraVolume:
    Type: String
    AllowedValues: ["true", "false"]
    Default: "false"
    Description: "Whether to attach an additional gp3 volume"

  ExtraVolumeSize:
    Type: Number
    Default: 20
    Description: "Size (GiB) of the optional additional volume"

  SecurityGroupName:
    Type: String
    Description: "Security Group Name"

Conditions:
  AddExtraVolume: !Equals [!Ref AttachExtraVolume, "true"]
  UsePublicIp: !Equals [!Ref AssignPublicIp, "true"]

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow SSH (22)"
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Ref SecurityGroupName

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AMIId
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref SubnetExportName
          GroupSet:
            - !Ref InstanceSecurityGroup
          AssociatePublicIpAddress: !If [UsePublicIp, true, false]
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: !Ref RootVolumeSize
            VolumeType: gp3
            DeleteOnTermination: true
        - !If
          - AddExtraVolume
          - DeviceName: /dev/sdf
            Ebs:
              VolumeSize: !Ref ExtraVolumeSize
              VolumeType: gp3
              DeleteOnTermination: true
          - !Ref AWS::NoValue
      Tags:
        - Key: Name
          Value: !Ref InstanceName

Outputs:
  InstanceId:
    Description: "The ID of the EC2 instance"
    Value: !Ref EC2Instance
    Export:
      Name: !Sub "${InstanceName}-ID"
